kind: pipeline
name: default
steps:
  - name: install
    image: composer
    commands:
      - composer install
  - name: git-push
    image: drone-git-push
    settings:
      branch: features/discord-bot
      remote: git.rotour.dev
      force: false
      commit: true