kind: pipeline
name: default
type: docker

steps:
  - name: docker image front
    image: docker-front
    settings:
      dockerfile: api/Dockerfile
      when:
        event:
          -push
  - name: docker image back
    image: docker-back
    settings:
      dockerfile: bot/Dockerfile
      when:
        event:
          -push