kind: pipeline
name: default
type: docker

steps:
  - name: build-api
    image: docker:latest
    commands:
      - docker build -t laphant:api api/
    volumes:
      - name: docker_socket
        path: /var/run/docker.sock
#  - name: build-bot
#    image: docker:latest
#    commands:
#      - docker build -t laphant:bot bot/
#    volumes:
#      - name: docker_socket
#        path: /var/run/docker.sock
  - name: deploy
    image: docker/compose
    volumes:
      - name: app
        path: /app/docker-compose.yml
      - name: docker_socket
        path: /var/run/docker.sock
    commands:
      - cd /app
      - docker-compose up -d laphant-api #laphant-bot


volumes: #share file between container and host
  - name: docker_socket
    host:
      path: /var/run/docker.sock
  - name: app
    host:
      path: /home/lucas/LAphant/docker-compose.yaml