kind: pipeline
name: default
type: docker

steps:
  - name: build-api
    image: docker:latest
    commands:
      - docker build -t laphant:api api/
    volumes:
      - name: docker_socket
        path: /var/run/docker.sock


volumes: #share file between container and host
  - name: docker_socket
    host:
      path: /var/run/docker.sock